create table employees (id int8 generated by default as identity, email_id varchar(255), first_name varchar(255), last_name varchar(255), primary key (id));
create table employees (id int8 generated by default as identity, email_id varchar(255), first_name varchar(255), last_name varchar(255), primary key (id));
